### ISSUE TITLE
The web site at chrom has problem

### ISSUE THREAD

**Issue by reza1615** [sdouglas/excel2wiki#3]
when I open [this page](https://tools.wmflabs.org/excel2wiki/index.php) in chrome. a white window pops up and doesn't allow to see the page.
please solve it.
P.S. In firfox it is ok
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by sdouglas** [comment]
You'll want to contact the current maintainer of that page: [Ahecht](https://en.wikipedia.org/wiki/User:Ahecht).
